# Generated by Django 6.0.2 on 2026-03-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restructure_for_content_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Secção', 'verbose_name_plural': 'Secções'},
        ),
        migrations.AlterModelOptions(
            name='contentsection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='mapcomparison',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Comparação de mapa', 'verbose_name_plural': 'Comparações de mapa'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Média', 'verbose_name_plural': 'Médias'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulo (EN)'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.subcategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Texto (PT)'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Texto (EN)'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='app.contentsection', verbose_name='Conteúdo pai'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.category', verbose_name='Secção'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulo (EN)'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='caption_after',
            field=models.CharField(default='Depois', max_length=100, verbose_name='Legenda depois'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='caption_before',
            field=models.CharField(default='Antes', max_length=100, verbose_name='Legenda antes'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='app.contentsection', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='image_after',
            field=models.ImageField(upload_to='maps/after/', verbose_name='Imagem depois'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='image_before',
            field=models.ImageField(upload_to='maps/before/', verbose_name='Imagem antes'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='mapcomparison',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.contentsection', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/%Y/%m/', verbose_name='Ficheiro'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_zoomable',
            field=models.BooleanField(default=True, verbose_name='Permite zoom'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Video'), ('map', 'Mapa')], default='image', max_length=10, verbose_name='Tipo de media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.subcategory', verbose_name='Categoria pai'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category', verbose_name='Secção'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulo (EN)'),
        ),
    ]
