# Generated by Django 6.0.2 on 2026-03-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_alter_contentsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
