# Generated by Django 6.0.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_media_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='app.contentsection', verbose_name='Subcategoria de'),
        ),
    ]
