# Generated by Django 6.0.2 on 2026-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_slug_alter_contentsection_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Legenda (EN)'),
        ),
    ]
