# Generated by Django 6.0.2 on 2026-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_media_caption_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/display_1920/', verbose_name='Miniatura'),
        ),
    ]
