# Generated by ChatGPT on 2026-03-06

from decimal import Decimal

from django.db import migrations, models


MAP_AREA_ROWS = [
    ("Cunha", "Pico do Ferro", "0.441758449"),
    ("Domos 1 e 2", "Pico do Ferro", "5.197394558"),
    ("Domos 3, 4 e 5", "Pico do Ferro", "13.85143388"),
    ("Domos 3, 4 e 5 - Terreno fora da BHLF", "Pico do Ferro", "1.823287541"),
    ("Gaiteira - Casa Caída", "Gaiteira", "0.577404999"),
    ("Parcela 10", "Terra Cega - Achada", "31.14581911"),
    ("Parcela 11", "Matos da Cafua", "25.94710821"),
    ("Parcela 15", "Terra Cega - Achada", "13.00092203"),
    ("Parcela 25", "Terra Cega - Achada", "16.14754095"),
    ("Parcela 31", "Fajã das Rabaças", "1.640689234"),
    ("Parcela 35 - SATUR", "Rua da Lagoa das Furnas, n.º 1489", "15.27338141"),
    ("Parcela 37", "Boca da Grota", "11.60915226"),
    ("Parcela 37 (Grota do Rosal)", "Boca da Grota", "7.625834091"),
    ("Parcela 38", "Boca da Grota", "18.80338035"),
    ("Parcela 39", "Grota do Diogo Preto", "41.06816872"),
    ("Parcela 48", "Covões", "5.270507612"),
    ("Parcela 6", "Touro", "65.00850716"),
    ("Pastagem Domo", "Pico do Ferro - Furnas", "5.546185161"),
    ("Pomar", "Pomar", "6.090422205"),
    ("Terra Escondida", "Pico do Ferro", "1.246010797"),
]


def seed_map_area_info(apps, schema_editor):
    ContentSection = apps.get_model("app", "ContentSection")
    MapAreaInfo = apps.get_model("app", "MapAreaInfo")

    target = ContentSection.objects.filter(slug="aquisicao-de-terrenos").first()
    if not target:
        return

    MapAreaInfo.objects.filter(content_id=target.id).delete()
    MapAreaInfo.objects.bulk_create(
        [
            MapAreaInfo(
                content_id=target.id,
                area_index=index,
                title=title,
                location=location,
                area_ha=Decimal(area_ha),
            )
            for index, (title, location, area_ha) in enumerate(MAP_AREA_ROWS)
        ]
    )


def unseed_map_area_info(apps, schema_editor):
    ContentSection = apps.get_model("app", "ContentSection")
    MapAreaInfo = apps.get_model("app", "MapAreaInfo")
    target = ContentSection.objects.filter(slug="aquisicao-de-terrenos").first()
    if not target:
        return
    MapAreaInfo.objects.filter(content_id=target.id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_media_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapAreaInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area_index", models.PositiveIntegerField(default=0, verbose_name="Indice da área (SVG)")),
                ("title", models.CharField(max_length=255, verbose_name="Designação")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Local")),
                (
                    "area_ha",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name="Area (ha)"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="map_areas",
                        to="app.contentsection",
                        verbose_name="Conteúdo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área do mapa",
                "verbose_name_plural": "Áreas do mapa",
                "ordering": ["area_index", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "area_index"),
                        name="uniq_map_area_index_per_content",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_map_area_info, unseed_map_area_info),
    ]
