# Generated by ChatGPT on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_mapareainfo_and_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapareainfo",
            name="fill_color",
            field=models.CharField(
                blank=True,
                help_text="Hex/RGBA (ex: #34a853)",
                max_length=32,
                verbose_name="Cor da área",
            ),
        ),
    ]
