# Generated by ChatGPT on 2026-03-06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_mapareainfo_fill_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mapareainfo",
            name="uniq_map_area_index_per_content",
        ),
    ]
