# Generated by ChatGPT on 2026-03-06

from django.db import migrations, models


def backfill_legend_order(apps, schema_editor):
    MapAreaInfo = apps.get_model("app", "MapAreaInfo")
    for row in MapAreaInfo.objects.all().only("id", "area_index"):
        row.legend_order = row.area_index
        row.save(update_fields=["legend_order"])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_map_area_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapareainfo",
            name="legend_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem da legenda"),
        ),
        migrations.RunPython(backfill_legend_order, migrations.RunPython.noop),
    ]
