# Generated by Django 6.0.2 on 2026-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mapareainfo_legend_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geopark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Nome (EN)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='Data de adesão')),
                ('description_pt', models.TextField(blank=True, verbose_name='Introdução (PT)')),
                ('description_en', models.TextField(blank=True, verbose_name='Introduction (EN)')),
                ('quote_pt', models.CharField(blank=True, max_length=500, verbose_name='Frase (PT)')),
                ('quote_en', models.CharField(blank=True, max_length=500, verbose_name='Quote (EN)')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Área (km²)')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='População')),
            ],
            options={
                'verbose_name': 'Geoparque',
                'verbose_name_plural': 'Geoparques',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mapareainfo',
            options={'ordering': ['legend_order', 'id'], 'verbose_name': 'Área do mapa', 'verbose_name_plural': 'Mapa Aquisição'},
        ),
    ]
