# Generated by Django 6.0.2 on 2026-03-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_geopark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_zoomable',
        ),
        migrations.DeleteModel(
            name='MapComparison',
        ),
    ]
