# Generated by Django 6.0.2 on 2026-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_mapcomparison_is_zoomable'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='group',
            field=models.CharField(blank=True, help_text='Imagens com o mesmo grupo são mostradas em carrossel (ex: A, B, C…)', max_length=10, verbose_name='Grupo'),
        ),
    ]
