# Generated by Django 6.0.2 on 2026-03-23 15:22

from django.db import migrations
import string


def assign_groups(apps, schema_editor):
    """
    For each ContentSection, find images that share the same caption (PT).
    Groups of 2+ shared-caption images are assigned letters A, B, C…
    Single images with a unique caption keep an empty group.
    """
    Media = apps.get_model('app', 'Media')
    ContentSection = apps.get_model('app', 'ContentSection')

    letters = list(string.ascii_uppercase)

    for content in ContentSection.objects.all():
        media_qs = Media.objects.filter(content=content).order_by('order', 'id')

        # Count how many times each caption appears
        caption_counts = {}
        for m in media_qs:
            key = (m.caption or '').strip().lower()
            if key:
                caption_counts[key] = caption_counts.get(key, 0) + 1

        # Only captions that appear more than once get a group letter
        caption_to_letter = {}
        letter_idx = 0
        for m in media_qs:
            key = (m.caption or '').strip().lower()
            if key and caption_counts.get(key, 0) > 1:
                if key not in caption_to_letter:
                    caption_to_letter[key] = letters[letter_idx % len(letters)]
                    letter_idx += 1
                m.group = caption_to_letter[key]
                m.save(update_fields=['group'])


def reverse_assign_groups(apps, schema_editor):
    Media = apps.get_model('app', 'Media')
    Media.objects.update(group='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_media_group'),
    ]

    operations = [
        migrations.RunPython(assign_groups, reverse_assign_groups),
    ]
