# Generated by Django 6.0.2 on 2026-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_populate_media_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pt', models.CharField(default='Bacia Hidrográfica das Furnas', max_length=200, verbose_name='Título (PT)')),
                ('title_en', models.CharField(default='Furnas Watershed', max_length=200, verbose_name='Title (EN)')),
                ('subtitle_pt', models.CharField(default='Plano de Ordenamento', max_length=200, verbose_name='Subtítulo (PT)')),
                ('subtitle_en', models.CharField(default='Land Management Plan', max_length=200, verbose_name='Subtitle (EN)')),
            ],
            options={
                'verbose_name': 'Configurações do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
