# Generated by Django 6.0.2 on 2026-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_site_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configurações', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kiosk_ip',
            field=models.CharField(blank=True, help_text='Endereço IP do kiosk interativo (ex: 192.168.1.50)', max_length=100, verbose_name='IP do Kiosk'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='screensaver_timeout',
            field=models.PositiveIntegerField(default=60, verbose_name='Tempo para screensaver (s)'),
        ),
    ]
